/*
 * Copyright (C) 2021-2022 Rick Busarow
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package modulecheck.parsing.source

/**
 * Indicates that a given [DeclaredName] is generated by some mechanism, like AGP or Dagger.
 *
 * @since 0.12.0
 */
sealed interface Generated : McName {

  /**
   * The references which the underlying code generator (AGP, Dagger, etc.) uses in order to trigger
   * the new declaration.
   *
   * @since 0.12.0
   */
  val sources: Set<ReferenceName>
}
