/*
 * Copyright (C) 2021 Rick Busarow
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package modulecheck.gradle

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.TypeSpec
import hermit.test.junit.HermitJUnit5
import hermit.test.resets
import io.kotest.matchers.collections.shouldContain
import modulecheck.specs.*
import modulecheck.testing.tempDir
import org.gradle.testkit.runner.BuildResult
import org.gradle.testkit.runner.GradleRunner
import org.gradle.testkit.runner.TaskOutcome
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.TestInfo
import java.io.File
import java.nio.file.Path
import io.kotest.matchers.shouldBe as kotestShouldBe

val DEFAULT_GRADLE_VERSION: String = System.getProperty("modulecheck.gradleVersion", "7.0")

abstract class BaseTest : HermitJUnit5() {

  val testProjectDir by tempDir()

  fun File.relativePath() = path.removePrefix(testProjectDir.path)

  fun String.fixPath(): String = replace(File.separator, "/")

  private val kotlinVersion =
    System.getProperty("modulecheck.kotlinVersion", DEFAULT_KOTLIN_VERSION)
  private val agpVersion = System.getProperty("modulecheck.agpVersion", DEFAULT_AGP_VERSION)
  private val gradleVersion =
    System.getProperty("modulecheck.gradleVersion", DEFAULT_GRADLE_VERSION)

  val gradleRunner by resets {
    GradleRunner
      .create()
      .forwardOutput()
      .withGradleVersion(gradleVersion)
      .withPluginClasspath()
      // .withDebug(true)
      .withProjectDir(testProjectDir)
  }

  private var testInfo: TestInfo? = null

  fun build(vararg tasks: String): BuildResult {
    return gradleRunner.withArguments(*tasks).build()
  }

  fun BuildResult.shouldSucceed() {
    tasks.forEach { it.outcome shouldBe TaskOutcome.SUCCESS }
  }

  fun shouldFailWithMessage(vararg tasks: String, messageBlock: (String) -> Unit) {
    val result = gradleRunner.withArguments(*tasks).buildAndFail()

    result.tasks.map { it.outcome } shouldContain TaskOutcome.FAILED
    messageBlock(result.output.fixPath())
  }

  @BeforeEach
  fun beforeEach(testInfo: TestInfo) {
    this.testInfo = testInfo
  }

  @AfterEach
  fun afterEach() {
    testInfo = null
  }

  @Suppress("UNCHECKED_CAST", "NOTHING_TO_INLINE")
  infix fun <T, U : T> T.shouldBe(expected: U?) {
    /*
    Any AssertionError generated by this function will have this function at the top of its stacktrace.

    The actual call site for the assertion is always the _second_ line.

    So, we can catch the assertion error, remove this function from the stacktrace, and rethrow.
     */
    try {
      kotestShouldBe(expected)
    } catch (assertionError: AssertionError) {
      // remove this function from the stacktrace and rethrow
      assertionError.stackTrace = assertionError
        .stackTrace
        .drop(1)
        .toTypedArray()
      throw assertionError
    }
  }
}

@Suppress("LongParameterList")
fun jvmSubProject(
  path: String,
  vararg fqClassName: ClassName,
  apiDependencies: List<ProjectSpec> = emptyList(),
  implementationDependencies: List<ProjectSpec> = emptyList(),
  androidTestDependencies: List<ProjectSpec> = emptyList(),
  testDependencies: List<ProjectSpec> = emptyList()
): ProjectSpec = ProjectSpec(path) {
  addBuildSpec(
    ProjectBuildSpec {
      addPlugin("kotlin(\"jvm\")")
      applyEach(apiDependencies) { addProjectDependency("api", it) }
      applyEach(implementationDependencies) { addProjectDependency("implementation", it) }
      applyEach(androidTestDependencies) { addProjectDependency("androidTestImplementation", it) }
      applyEach(testDependencies) { addProjectDependency("testImplementation", it) }
    }
  )
    .applyEach(fqClassName.toList()) { fq ->
      addSrcSpec(
        ProjectSrcSpec(Path.of("src/main/kotlin")) {
          addFileSpec(
            FileSpec.builder(fq.packageName, fq.simpleName)
              .addType(TypeSpec.classBuilder(fq.simpleName).build())
              .build()
          )
        }
      )
    }
}
