# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
      - dependabot[bot]
      - renovate
      - renovate[bot]
      - renovate-bot
      - kodiakhq
      - kodiakhq[bot]

  categories:
    - title: 📐 New Rules
      labels:
        - New Rule
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 💥 Breaking Changes
      labels:
        - api-breaking change
    - title: 🐛 Bug Fixes
      labels:
        - fix
        - bugfix
        - bug
    - title: 🧰 Maintenance
      labels:
        - chore
        - dependencies
    - title: ℹ️ Website
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
