name: 'Commit and push changes from a shell command'
description: 'This action performs common steps for a specific shell command.'

inputs:
  working-directory:
    description: 'The working directory for the shell command execution'
    required: false
    default: '.'
  fix-command:
    description: 'The command to be executed if the user has a PAT and the branch is not a fork'
    required: true
  check-command:
    description: 'The command to be executed if the user does not have a PAT or the branch is a fork'
    required: false
  commit-message:
    description: 'The commit message to use if changes are generated'
    default: ''
  personal-access-token:
    description: 'The personal access token to use for checkouts'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check if PERSONAL_ACCESS_TOKEN is set
      id: can-push
      shell: bash
      run: |
        if [[ ${{ inputs.personal-access-token }} == '' ]]; then
          echo "can_push=false" >> $GITHUB_OUTPUT
        elif [[ ${{ github.event.pull_request.head.repo.full_name }} != ${{ github.repository }} ]]; then
          echo "can_push=false" >> $GITHUB_OUTPUT
        else
          echo "can_push=true" >> $GITHUB_OUTPUT
        fi

    - name: check out with PAT
      uses: actions/checkout@v3
      if: steps.can-push.outputs.can_push == 'true'
      with:
        token: ${{ inputs.personal-access-token }}
        fetch-depth: 0

    - name: Run ${{ inputs.fix-command }}
      if: steps.can-push.outputs.can_push == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ${{ inputs.fix-command }}

    - name: Set Commit Message
      id: set-commit-message
      if: steps.can-push.outputs.can_push == 'true'
      shell: bash
      run: |
        if [[ -z "${{ inputs.commit-message }}" ]]; then
          echo "commit-message=Apply changes from ${{ inputs.fix-task }}" >> $GITHUB_OUTPUT
        else
          echo "commit-message=${{ inputs.commit-message }}" >> $GITHUB_OUTPUT
        fi

    - name: commit ${{ inputs.fix-task }} changes
      if: steps.can-push.outputs.can_push == 'true'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ${{ steps.set-commit-message.outputs.commit-message }}
        commit_options: '--no-verify --signoff'

    - name: Run ${{ inputs.check-task }}
      if: steps.can-push.outputs.can_push != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ${{ inputs.check-command }}
