name: Delete Unused Caches

on:
  pull_request:
    types: [ closed ]

jobs:

  # This deletes the caches created by the branch while it was in PR.
  # Those caches are inaccessible to it once it's merged, so they can be deleted.
  delete-orphaned-caches:
    runs-on: ubuntu-latest
    steps:
      - uses: snnaplab/delete-branch-cache-action@v1
        with:
          # Specify explicitly because the ref at the time of merging
          # will be a branch name such as 'main', 'develop'
          ref: refs/pull/${{ github.event.number }}/merge
