name: DependencySync

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - main

jobs:
  cancel-other-jobs:

    runs-on: ubuntu-latest

    steps:
      # cancel previous jobs
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  build:

    runs-on: ubuntu-latest

    steps:

      - name: check out with token (used by forks)
        uses: actions/checkout@v3
        if: github.event.pull_request.head.repo.full_name != github.repository

      - name: check out with PAT (used by main repo)
        uses: actions/checkout@v3
        if: github.event.pull_request.head.repo.full_name == github.repository
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'

      - name: run dependencySync
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
          arguments: |
            dependencySync
          concurrent: true
          gradle-build-scan-report: false

      # If the copy generated changes, commit and push those changes.
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: sync dependency definitions
          commit_options: '--no-verify --signoff'
