name: DependencySync

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - main

jobs:
  cancel-other-jobs:

    runs-on: ubuntu-latest

    steps:
      # cancel previous jobs
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        env:
          access_token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses : actions/setup-java@v2
        with :
          distribution : 'adopt'
          java-version : '14'
          cache: 'gradle'

      - uses: actions/cache@v2
        with:
          path: |
            ~/buildSrc/.gradle
            ~/buildSrc/build
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: run dependencySync
        run: ./gradlew dependencySync --no-daemon

      # If the copy generated changes, commit and push those changes.
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: sync dependency definitions
          commit_options: '--no-verify --signoff'
