name: main-updated

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:

  build-all:
    runs-on: macos-latest
    if: github.repository == 'rickbusarow/ModuleCheck'
    steps:
      - name: check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: main build
        uses: rickbusarow/actions/gradle-task@c602f8da97f00279c6e77d3f25cbedcbf24ef936 # v1
        with:
          task: jar compileKotlin
          restore-cache-key: build-logic-jar
          write-cache-key: main-build-artifacts

  publish-snapshot:
    needs:
      - build-all
    runs-on: macos-latest

    steps:
      - name: check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Publish Snapshots
        uses: rickbusarow/actions/gradle-task@c602f8da97f00279c6e77d3f25cbedcbf24ef936 # v1
        with:
          task: publish
          write-cache-key: local-m2
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}

  publish-website:
    needs:
      - build-all
    runs-on: macos-latest
    steps:
      - name: check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: dokkaGenerate
        uses: rickbusarow/actions/gradle-task@c602f8da97f00279c6e77d3f25cbedcbf24ef936 # v1
        with:
          task: dokkaGenerate
          restore-cache-key: main-build-artifacts
          write-cache-key: dokka-build-artifacts

      - name: website build cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: |
            website/.docusaurus
            website/build
            website/node_modules
          key: website-build
          enableCrossOsArchive: true

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          version: 8

      # Node is required for pnpm
      - name: Set up Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 18
          cache: pnpm
          cache-dependency-path: website/pnpm-lock.yaml

      - name: Install Pnpm
        working-directory: website
        run: pnpm install --no-lockfile

      - name: build website
        uses: rickbusarow/actions/gradle-task@c602f8da97f00279c6e77d3f25cbedcbf24ef936 # v1
        with:
          task: buildSite
          write-cache-key: website-build

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@df5cc2bfa78282ded844b354faee141f06b41865 # v4
        with:
          target_branch: gh-pages
          build_dir: website/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
