name: main-updated

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:

  build-logic:
    runs-on: macos-latest
    steps:
      - name: check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: build build-logic
        uses: rickbusarow/actions/gradle-task@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          task: :build-logic:compileKotlin :build-logic:jar
          write-cache-key: build-logic-jar

  build-all:
    runs-on: macos-latest
    steps:
      - name: check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: main build
        uses: rickbusarow/actions/gradle-task@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          task: jar compileKotlin
          restore-cache-key: build-logic-jar
          write-cache-key: main-build-artifacts

  publish-snapshot:
    needs:
      - build-all
    if: github.repository == 'RBusarow/ModuleCheck'
    runs-on: macos-latest

    steps:
      - name: check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Dokka & JavadocJar
        uses: rickbusarow/actions/gradle-task@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          task: dokkaJavadocJar
          restore-cache-key: main-build-artifacts

      - name: Publish Snapshots
        uses: rickbusarow/actions/gradle-task@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          task: publish
          write-cache-key: local-m2
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}

  publish-website:
    needs:
      - build-all
    runs-on: macos-latest
    steps:
      - name: check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: dokkaHtmlMultiModule
        uses: rickbusarow/actions/gradle-task@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          task: dokkaHtmlMultiModule
          restore-cache-key: main-build-artifacts
          write-cache-key: dokka-build-artifacts

      - name: website build cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: |
            website/.docusaurus
            website/build
            website/node_modules
          key: website-build
          enableCrossOsArchive: true

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      # Node is required for pnpm
      - name: Set up Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 18
          cache: pnpm
          cache-dependency-path: website/pnpm-lock.yaml

      - name: Install Pnpm
        working-directory: website
        run: pnpm install --no-lockfile

      - name: build website
        uses: rickbusarow/actions/gradle-task@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          task: buildSite
          write-cache-key: website-build

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@c05ee637ec73429400a359430db8e5629f3f2564 # v4
        with:
          target_branch: gh-pages
          build_dir: website/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
