name: Publish snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GRADLE_OPTS_WINDOWS: >
    -Dorg.gradle.jvmargs=" -Xmx3g -XX:MaxMetaspaceSize=756m -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
    -Dorg.gradle.configureondemand=false
    -Dorg.gradle.parallel=false
    -Dkotlin.incremental=false
  GRADLE_OPTS_MACOS: >
    -Dorg.gradle.jvmargs=" -Xmx10g -XX:MaxMetaspaceSize=756m -XX:MaxPermSize=4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
    -Dorg.gradle.configureondemand=false
    -Dorg.gradle.parallel=false
    -Dkotlin.incremental=false
  GRADLE_OPTS_UBUNTU: >
    -Dorg.gradle.jvmargs=" -Xmx5g -XX:MaxMetaspaceSize=756m -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
    -Dorg.gradle.configureondemand=false
    -Dorg.gradle.parallel=false
    -Dkotlin.incremental=false

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    if: github.repository == 'RBusarow/ModuleCheck'
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set GRADLE_OPTS for OS
        uses: ./.github/actions/gradle-opts

      # break the publishing builds down a little into smaller steps
      # because gradle-build-action's caching is all-or-nothing.  If the full publish task
      # takes too long and times out, no cache is retained.

      - name: Compile Kotlin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: compileKotlin

      - name: Dokka & JavadocJar
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dokkaJavadocJar

      - name: Publish Snapshots
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
