name: Publish snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-snapshot :
    runs-on : ubuntu-latest
    if : github.repository == 'RBusarow/ModuleCheck'
    timeout-minutes : 25

    steps :
      - uses : actions/checkout@v2
      - uses : actions/setup-java@v2
        with :
          distribution : 'temurin'
          java-version : '11'
          check-latest : true

      - name : Publish Snapshots
        run : ./gradlew clean publish --no-build-cache --no-daemon --stacktrace --no-parallel
        env :
          ORG_GRADLE_PROJECT_mavenCentralUsername : ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword : ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
