name: Publish snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  macosGradleArgs: '-Dorg.gradle.jvmargs=-Xmx10g'
  ubuntuGradleArgs: '-Dorg.gradle.jvmargs=-Xmx5g'
  windowsGradleArgs: '-Dorg.gradle.jvmargs=-Xmx5g'

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    if: github.repository == 'RBusarow/ModuleCheck'
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      # break the publishing builds down a little into smaller steps
      # because gradle-build-action's caching is all-or-nothing.  If the full publish task
      # takes too long and times out, no cache is retained.

      - name: Compile Kotlin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: compileKotlin "${{ env.ubuntuGradleArgs }}"

      - name: Dokka & JavadocJar
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dokkaJavadocJar "${{ env.ubuntuGradleArgs }}"

      - name: Publish Snapshots
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish "${{ env.ubuntuGradleArgs }}"
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
